name: ThornyaWeb
author: Thornya.Club
description: Uma integração do Whatsapp + Servidor
main: club.thornya.thornyaweb.ThornyaWeb
website: https://github.com/Thornya-Club/ThornyaWeb
version: ${project.version}
api-version: 1.16